Day 1/NetCoreWebAppFlavors/WebAppCore.MVC/Models/BoardGame.cs
using System.ComponentModel;

namespace WebAppCore.MVC.Models
{
    public class BoardGame
    {
        public int ID { get; set; }
        public string Title { get; set; }

        [DisplayName("Publishing Company")]
        public string PublishingCompany { get; set; }

        [DisplayName("Min Players")]
        public int MinPlayers { get; set; }

        [DisplayName("Max Players")]
        public int MaxPlayers { get; set; }
    }
}

Day 1/NetCoreWebAppFlavors/WebAppCore.MVC/Models/DataGenerator.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Linq;
using WebAppCore.MVC.DataContext;

namespace WebAppCore.MVC.Models
{
    public class DataGenerator
    {

        public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new BoardGamesDBContext(serviceProvider.GetRequiredService<DbContextOptions<BoardGamesDBContext>>()))
            {
                // Look for any board games already in database.
                if (context.BoardGames.Any())
                {
                    return;   // Database has been seeded
                }

                context.BoardGames.AddRange(
                    new BoardGame
                    {
                        ID = 1,
                        Title = "Candy Land",
                        PublishingCompany = "Hasbro",
                        MinPlayers = 2,
                        MaxPlayers = 4
                    },
                    new BoardGame
                    {
                        ID = 2,
                        Title = "Sorry!",
                        PublishingCompany = "Hasbro",
                        MinPlayers = 2,
                        MaxPlayers = 4
                    },
                    new BoardGame
                    {
                        ID = 3,
                        Title = "Ticket to Ride",
                        PublishingCompany = "Days of Wonder",
                        MinPlayers = 2,
                        MaxPlayers = 5
                    },
                    new BoardGame
                    {
                        ID = 4,
                        Title = "The Settlers of Catan (Expanded)",
                        PublishingCompany = "Catan Studio",
                        MinPlayers = 2,
                        MaxPlayers = 6
                    },
                    new BoardGame
                    {
                        ID = 5,
                        Title = "Carcasonne",
                        PublishingCompany = "Z-Man Games",
                        MinPlayers = 2,
                        MaxPlayers = 5
                    },
                    new BoardGame
                    {
                        ID = 6,
                        Title = "Sequence",
                        PublishingCompany = "Jax Games",
                        MinPlayers = 2,
                        MaxPlayers = 6
                    });

                context.SaveChanges();
            }
        }
    }
}

Day 1/NetCoreWebAppFlavors/WebAppCore.MVC/Models/ErrorViewModel.cs
using System;

namespace WebAppCore.MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Day 1/NetCoreWebAppFlavors/WebAppCore.MVC/Controllers/BoardGameController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using WebAppCore.MVC.DataContext;
using WebAppCore.MVC.Models;

namespace WebAppCore.MVC.Controllers
{
    public class BoardGameController : Controller
    {
        private readonly BoardGamesDBContext context;

        public BoardGameController(BoardGamesDBContext context)
        {
            this.context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var games = context.BoardGames.ToList();

            return View(games);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(BoardGame game)
        {
            //Determine the next ID
            var newID = context.BoardGames.Select(x => x.ID).Max() + 1;

            game.ID = newID;

            context.BoardGames.Add(game);
            context.SaveChanges();
            
            return RedirectToAction("Index");
        }
    }
}

Day 1/NetCoreWebAppFlavors/WebAppCore.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebAppCore.MVC.Models;

namespace WebAppCore.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Day 1/NetCoreWebAppFlavors/WebAppCore.MVC/Views/BoardGame/Add.cshtml
@model WebAppCore.MVC.Models.BoardGame

@{
    ViewData["Title"] = "Add";
}

<h2>Add</h2>

<h4>BoardGame</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublishingCompany" class="control-label"></label>
                <input asp-for="PublishingCompany" class="form-control" />
                <span asp-validation-for="PublishingCompany" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MinPlayers" class="control-label"></label>
                <input asp-for="MinPlayers" class="form-control" />
                <span asp-validation-for="MinPlayers" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxPlayers" class="control-label"></label>
                <input asp-for="MaxPlayers" class="form-control" />
                <span asp-validation-for="MaxPlayers" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Day 1/NetCoreWebAppFlavors/WebAppCore.MVC/Views/BoardGame/Index.cshtml
@model IEnumerable<WebAppCore.MVC.Models.BoardGame>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Add">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublishingCompany)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MinPlayers)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaxPlayers)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PublishingCompany)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MinPlayers)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaxPlayers)
                </td>
            </tr>
        }
    </tbody>
</table>

Day 1/NetCoreWebAppFlavors/WebAppCore.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAppCore.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAppCore.MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BoardGame" asp-action="Index">Board Games</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - WebAppCore.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>